### ISSUE TITLE
'Promise' only refers to a type, but is being used as a value here.

### ISSUE THREAD

**Issue by peter-leonov** [agentcooper/typescript-play#19]
https://agentcooper.github.io/typescript-play/#code/AoJw9gtglgzgpgOhHGYA2A3OAKALiAVzgEoAoIA

😲

**Comment by ajafff** [comment]
simply use a `target` greater than or equal to ES2015. That's the language version that introduced Promise

**Comment by peter-leonov** [comment]
Thanks! Works like a charm 👍
Don't you think of making it the default to have the full power by default as it's a playground where people beat the best out of the language?

**Comment by agentcooper** [comment]
Makes sense! I changed the default target to ES2017.
