### ISSUE TITLE
Include compiler options in share url

### ISSUE THREAD

**Issue by agentcooper** [agentcooper/typescript-play#2]
Maybe this should be optional.

**Comment by SimonMeskens** [comment]
I'd really like to get this one in, because right now, if I share code samples, they have errors in them due to the compile target defaulting to ES3. If nothing else, the default should be ESNext to cause the least amount of errors.

**Comment by agentcooper** [comment]
Done.

**Comment by SimonMeskens** [comment]
Super, thanks!
