### ISSUE TITLE
Add support for newer TypeScript

### ISSUE THREAD

**Issue by NN---** [agentcooper/typescript-play#23]
3.1.0 , 3.2.0, 3.3.0 nightly

**Comment by agentcooper** [comment]
I've updated to 3.1.6 and once https://github.com/Microsoft/monaco-typescript/pull/27 lands I'll just point to the `latest` of `monaco-editor` – it would be easier to keep up to date. Still not sure what is the best process for nightlies though.

**Comment by NN---** [comment]
Could you add 3.2.1 which was just released please?
Currently I still.have to use MS TS playground.
Actually I would like MS to adapt this one and drop theirs.

**Comment by agentcooper** [comment]
I've updated to 3.2.1. The process is still quite manual, unfortunately.
