### ISSUE TITLE
Adding @types to the session

### ISSUE THREAD

**Issue by karol-majewski** [agentcooper/typescript-play#26]
I know it might sound like a big ask, but I believe having type definitions for 3rd party library would make this playground an order of magnitude better than the official one (and StackBlitz in some cases).

If this tool is currently used for:

- Prototyping & experimenting with your teammates
- Asking and answering questions on StackOverflow
- Sharing proofs of concept

than _not_ being able to install external typings would be the only reason you would go somewhere else.

What do you think?

**Comment by agentcooper** [comment]
This is definitely doable.

To load definitions for, let's say `react`, we need to fetch `https://unpkg.com/@types/react@16.7.18/index.d.ts` and then recursively fetch all references, like `<reference path="global.d.ts" />`.

**Comment by karol-majewski** [comment]
Something like that: https://github.com/stackblitz/core/blob/b2d397003ba393975abbca82fd8759d158b6e7f9/turbo-cdn/index.js#L25-L56

**Comment by orta** [comment]
This is working in the new TypeScript fork: [formik example](https://www.typescriptlang.org/play/?jsx=2#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwCwAUKJLHAN5yUB2AJllHAC+cIiXKU8MALQ8StRs2jwyAOgD0qANZYANlhgQuK3KlTym4JeXUhkwIybP0GCy6w4AxaCGCaANHAewLo8AV5QIGHevgCC+MCG6MKipGQE0ZrmClww-AR4WHAAasg6AK5Y6GyMcCLAUKgwAHLIIFgAXHCNUPYA5s61OmjNrR1dMD1c-TVwWLbAOp3dfc6CjIy4ifAAQmjAuJ3YkioAyh4AwgA8bIIAfHAAvHAAFACUj-fPM5c8wABucFwQ1MLTaDwARJscnYuPxwbcZrVLgALACMt3CPk0cAAHnAACoATzAWBOuB6YBglzUaIRDFqSMxvkRDPswBgwFKJXKlQebGq9IZQoI9UaoLGZDIfhZQuBIzanUl0sFQtqczsi3IUplQjWKoZhhOZQARj4YHznn9ShVUJ1uTaAhxUPojab2RypkJOkzNHEOYlLvbKrd3g97gLVQznTB8aAsBAyjBnm8PuwdULSvwkwApE4AeSaKmWU2ABEJlutlQCXDKOh0AQATK9XgNI1GXSazR7es98jpnS300IAgBWAAMY8H+tqgj1ke4fCgFtDnyHl0xdLbDMuQ2NujgyJgIB04QhIoa8qw8KCF7g4upu90m63cHXwR0PDgwB4Z9Fl-BcBcKMv4XuKAFgEMuBYMiEAfvwELZhAyJcABMDElgEK5DiMAAWodJDkij46AeR4ntAEJymBtwADLDHeowPsge46M+W5viEX4-uClGjABQFgtxwxgXAEEFDBcFLuCAAiEBXnAaEkphWDYbh+HTqqO5Mfuh7Hqe4Lqgs8IAKLzDojHMaxbbsR+nEQgZOh8cB+mmeBkHQbBi4QgAVkhXAAAJ4G0xgkKh6F2S5cB4es6lCpcxqJgYXDyWF4KoJ27IAY0hJ6HyHC-KgomEoqxo6BAuCZLqllbq6ZoEa+ajxTAiVVduagbjqrxzgyUWCtSvx-HSU6MAu-DPJcuyoPskW3AEsi4GUbQ5CovT6EZeiLTA2yEgAkjwzwUBAEAwGQzbOEAA)

**Comment by karol-majewski** [comment]
It is! Thank you @orta.

**Comment by styfle** [comment]
@orta This is amazing!

How can I add types or even packages in the playground? I must be missing an option to "install" or "import"??

**Comment by orta** [comment]
It's automatic, just `import` something

**Comment by styfle** [comment]
@orta It seems like it works for types on DefinitelyTyped but not types shipped with the package?? Or perhaps I have a typo.

See [this playground](https://www.typescriptlang.org/play/#code/JYWwDg9gTgLgBAbzjCBhANsMAjCBDKAEzgF84AzKCEOAcgGMIwBTZ2gbgFgAoUSWOACo4eAM7I8LClRq0Yktl26MAdqIjpmAOnQQA5gAoYATxYRyyNJhz4iASiWr1mnfqOnm5iSwdA).

**Comment by orta** [comment]
Looks like a bug, you can see it trying to resolve the import to `https://www.unpkg.com/copee@1.0.6/index.d.ts` instead of `https://www.unpkg.com/copee@1.0.6/dist/index.d.ts` in the console 👍

**Comment by styfle** [comment]
@orta Thanks! Should I create a new issue?

**Comment by orta** [comment]
Sure, on the typescript-website repo 👍

**Comment by orta** [comment]
Fixed in https://github.com/orta/typescript-play/pull/13/commits/1924be24b708bd37c4b7b939df4e14f86b93b1b9
