### ISSUE TITLE
Playground with typescript 3.2.1 doesn't know about BigInt

### ISSUE THREAD

**Issue by ajafff** [agentcooper/typescript-play#27]
TS 3.2 added support for BigInt.
For some reason the Playground with ts 3.2.1 cannot parse BigInt literals and doesn't recognise the `bigint` type:
https://typescript-play.js.org/?target=6#code/IwOw3AUANgpgLgAgGYHsUC4ECMCWBzHEOMIA

**Comment by styfle** [comment]
This works now in the current playground (3.3.3)

**Comment by agentcooper** [comment]
@styfle Thanks for checking this. Closing the issue.
