### ISSUE TITLE
How to expose custom types and modules?

### ISSUE THREAD

**Issue by cisaacson** [agentcooper/typescript-play#42]
I am not sure how to expose custom types or modules that I create. Suppose I have a module in a file named '/myapp/src/my-module.ts' that exports various types. How would I make that available through the playground? Ideally I would like to be able to include types from our internal application and have them available in the console (we want to use the playground as a customized quick debugger).

I looked at Issue #26 and even getting a package like:

`import * as _ from 'lodash';` 

did not work (`lodash` is in your node_modules too).

An example of how to do all of this would be great.

**Comment by agentcooper** [comment]
Hey, you probably want to create this issue for [the official Playground](https://github.com/microsoft/TypeScript-Website/issues), as it now has all the same features and even more.
